name: Build LaTeX document
on:
  # schedule:
  #   - cron: "00 16 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - uses: actions/upload-artifact@v3
        with:
          name: mainpdf
          # path: /home/runner/work/brief-tiddlywiki5-introduction/brief-tiddlywiki5-introduction/dist/main.pdf
          path: dist/main.pdf
      - uses: actions/download-artifact@v3
        with:
          name: mainpdf
          path: dist/main.pdf

      - name: Display structure of downloaded files
        run: ls -R
        working-directory:
          dist/

          # - name: Release
          #   uses: softprops/action-gh-release@v1
          #   if: startsWith(github.ref, 'refs/tags/')
          #   with:
          #     files: |
          #       dist/main.pdf
